language: go
go:
- 1.6
addons:
  ssh_known_hosts: $HOST_IP
script: go test test/chaincode_example02_test.go
before_install:
- openssl aes-256-cbc -K $encrypted_9e054b26a25f_key -iv $encrypted_9e054b26a25f_iv
  -in chaincode_deploy_rsa.enc -out /tmp/chaincode_deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/chaincode_deploy_rsa
- ssh-add /tmp/chaincode_deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
  on:
    branch: master

